### ISSUE TITLE
proposed Module rename. -api => -http-client

### ISSUE THREAD

**Issue by daviddias** [ipfs/py-ipfs-http-client#140]
Hi! We are considering renaming the IPFS Client libraries, please read more at https://github.com/ipfs/ipfs/issues/374 and comment if you are onboard.

**Comment by daviddias** [comment]
@AliabbasMerchant go for it :)

**Comment by AliabbasMerchant** [comment]
I'll do it by this weekend, hopefully :+1:

**Comment by daviddias** [comment]
Thank you @AliabbasMerchant :)

**Comment by alexander255** [comment]
@AliabbasMerchant: So you'll submit a PR that renames this module and stuff?

**Comment by AliabbasMerchant** [comment]
Yes.  
And what do we do with the repo name?? I suppose we leave it as it is...

**Comment by daviddias** [comment]
@AliabbasMerchant it would be better to update it as well

**Comment by daviddias** [comment]
Github is pretty good at redirecting when renaming happens :)

**Comment by AliabbasMerchant** [comment]
Oh. Cool. I didn't know that.

**Comment by alexander255** [comment]
The more tricky thing will be renaming the Python library actually, since we'd either have to continue uploading it under both names or (again) deprecate the old one.

The best solution here is to use an “import redirect” to keep both versions working:

  * Upload a new version of the library under the new name
  * Create a totally new stub library with the same file structure as the current library that uses `from <new-name> import *` in each module to import the actual contents from the library's new import name and has a dependency on the actual library
     * The stub library should also emit a deprecation warning of course
  * Upload the newly created library under the old name

@AliabbasMerchant: Do you think you can create such a stub library as well to ease the transition for everybody?

**Comment by alexander255** [comment]
On the other hand there are some design issues I'd like to see resolved that would necessitate breaking the API a bit. Most of these could be kept backward-compatible using simple wrappers, so I think I'll use this chance to fix some stuff under the new name and write wrappers in a stub module as I mentioned above for back-compat. Basically I mean I'll take care of the compat issue myself, so you no need for you to waste any time on this :slightly_smiling_face:

**Comment by alexander255** [comment]
@all: [`py-ipfs-http-client` v0.4.11](https://pypi.org/project/ipfshttpclient/) and [`py-ipfs-api` v0.4.4](https://pypi.org/project/ipfsapi/) have finally been released! (The later now being a compat wrapper around the former.) Thanks everybody who helped make this happen! :confetti_ball: 

@daviddias: Please change the name of this repo to `py-ipfs-http-client`. And can we have an entry in the IPFS newsletter for this? :stuck_out_tongue: 

Also please add @AliabbasMerchant to the Python team, I offered him that title some time ago but unfortunately forgot about it.

**Comment by Stebalien** [comment]
Done.

**Comment by alexander255** [comment]
@Stebalien: Thank you! Can you also add @AliabbasMerchant to the team while your at it? 😀

**Comment by alexander255** [comment]
All renaming changes are done by now, closing.

**Comment by AliabbasMerchant** [comment]
I think I haven't been added to the team as yet. 😅

**Comment by alexander255** [comment]
I know :slightly_frowning_face: 

With the core team being so preoccupied its hard to get them to do the organizational changes required.

@Stebalien @daviddias @archingbrain @whyrusleeping: Please add @AliabbasMerchant to the Python team. (First one to act will receive this cookie: :cookie:)

**Comment by alexander255** [comment]
@daviddias: You'll get your cookie! But first: It doesn't seem like @AliabbasMerchant is showing up on the team's member list (https://github.com/orgs/ipfs/teams/repos-python/members), you'll have to finish the job first. :wink:

**Comment by daviddias** [comment]
@AliabbasMerchant needs to accept first
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/1211152/65117714-f22f2600-d9f2-11e9-9086-ef6f2b9707c0.png">

**Comment by AliabbasMerchant** [comment]
@alexander255 @daviddias I have accepted the invitation. Thanks a lot! 😃

**Comment by alexander255** [comment]
@daviddias: Oh, I see! Here's a special cookie from me too:
![BIIIGGG COOKIEEEEE](https://www.coldstonecreamery.com/assets/img/products/cookies/sandwiches-perfectduet.jpg)
