### ISSUE TITLE
add_bytes and add_string 

### ISSUE THREAD

**Issue by batrlatom** [ipfs/py-ipfs-http-client#188]
Python 3.7
py-ipfs-http-client ... last version

I have a problem with adding images in base64 format. The content is not added as a whole. Is there any limit to the size of the string or byte array?

Original to be added:
![image](https://user-images.githubusercontent.com/11804368/61075735-f0594d00-a41a-11e9-89d2-5a36d3813b0d.png)

What was added (as an example, not exactly the same image):
![image](https://user-images.githubusercontent.com/11804368/61075602-a1abb300-a41a-11e9-8db1-a0a96bbf1db4.png)

**Comment by alexander255** [comment]
Thanks for the report! Which version of go-ipfs are you using? There were some known issues with some recent versions regarding this.

Please run the following commands and report their results for this:
 * `ipfs version` (go-ipfs version)
 * `python3 -c 'import ipfshttpclient; print(ipfshttpclient.__version__)'` (py-ipfs-http-client version)

Will help you after this if I can!

**Comment by WouterGlorieux** [comment]
I'm also experiencing similar behavior when trying to add a string or json object larger than 4096 characters via ipfshttpclient

i'm using:
Python 3.7
go-ipfs 0.4.22
ipfshttpclient 0.4.12

i also tried downgrading go-ipfs to earlier versions, but the behaviour was the same, string get truncated at 4096 characters

Here is a bit of code to reproduce the behaviour:


`

    import ipfshttpclient

    api = ipfshttpclient.connect(’/ip4/127.0.0.1/tcp/5001/http’)

    length = 4097 # up to 4096 should work

    original_string = ‘’.join([‘a’ for _ in range(length)])
    multihash = api.add_str(original_string)

    retrieved_string = api.cat(cid=multihash)

    retrieved_string = retrieved_string.decode() # In python3, the retrieved string is a bytes object, so need to decode it back into a string

    print(original_string)
    print(retrieved_string)
    assert original_string == retrieved_string
`

**Comment by WouterGlorieux** [comment]
Just saw there is another open issue regarding this same problem:
https://github.com/ipfs/py-ipfs-http-client/issues/190

it mentions setting chunk_size when connecting to the ipfs node
`client = ipfshttpclient.connect('/ip4/127.0.0.1/tcp/5001/http"', chunk_size=4096, session=True)`

I have tried it and setting chunk_size to a larger number does work.

But would this cause any side effects if I set it to a very large number?

**Comment by WouterGlorieux** [comment]
Found the problem and created a pull request:
https://github.com/ipfs/py-ipfs-http-client/pull/194
