### ISSUE TITLE
add_bytes upload is broken for bigger files

### ISSUE THREAD

**Issue by yashh** [ipfs/py-ipfs-http-client#190]
When uploading images to IPFS (0.4.21 and 0.4.22) we noticed that images are getting cropped / incomplete. As you can see here the image below has nt been uploaded completely.

![QmYqkegz1i9BCMHHKb9FwSyMNEBu6r7NK6csZhekbSmdVR](https://user-images.githubusercontent.com/22153/63404478-42857a80-c398-11e9-8c68-b4046cc384bf.jpg)

`client = ipfshttpclient.connect('/ip4/127.0.0.1/tcp/5001/http"', chunk_size=4096, session=True)`

When I tweak chunk_size I see different result. When I use bigger chunk size the image upload works. 4096 or lower causes incomplete upload. Any idea how to fix this?

**Comment by AliabbasMerchant** [comment]
This is similar to #188 
Will be fixed by #194
