### ISSUE TITLE
looking for new maintainers

### ISSUE THREAD

**Issue by amstocker** [ipfs/py-ipfs-http-client#39]
Hello!  Recently I have not been as involved with this project as I would like to be, and it is likely that I will not have much time in the future (although I would still like to contribute from time to time).  Would anyone be interested in being a maintainer?  I will keep reviewing and merging PRs in the meantime but I think this project could use some love!

In the future I would like to have built some more abstraction on top of the core api (@jgraef @Mec-iS [python3-ipfs-api](https://github.com/jgraef/python3-ipfs-api) has some really awesome ideas), especially seeing as the IPFS team will be eventually rolling out some kick-ass features such as pub-sub.  So if anyone is interested in maintaining `py-ipfs-api` and giving it a face-lift, post here!

**Comment by Mec-iS** [comment]
Hi,
I couldn't follow as much as I wanted as well lately. I am interested in
following along and help, we can set up a plan with you guys, looking for
an agreement on a roadmap to have a clear evolution of the repo in mind.
Ciao!

**Comment by jgraef** [comment]
Hi,

unfortunately I'm really busy right now and can't even work on python3-ipfs-api. I'll come back when I have more time.

**Comment by whereswaldon** [comment]
@amstocker I'd be willing to help out if you're still looking for people.

**Comment by jbenet** [comment]
I think we are

**Comment by amstocker** [comment]
@whereswaldon I would be very happy if you were willing to help!

**Comment by whereswaldon** [comment]
@amstocker Okay, what's the next step?

**Comment by tweirick** [comment]
@amstocker @jbenet @whereswaldon I am also interested in helping. If you are still accepting helpers I will also need some guidance regarding the next step. 

I am working on a python based bioinformatics paper that uses the IPFS. So I am very interested in seeing the py-ipfs-api work well!

**Comment by whereswaldon** [comment]
@amstocker If you do want me to help out, don't I need contributor access to the repo?

**Comment by heaven00** [comment]
I would also love to help :)

**Comment by lgierth** [comment]
@whereswaldon I think you did get collab access in the meantime -- do you feel like py-ipfs-api is covered no, maintainer-wise, and this can be closed for now? I'm not very much into python but in the past few weeks activity here as looked pretty good :)

**Comment by alexander255** [comment]
@lgierth: A lost of that was me sending cleanup patches and fixing bugs & design issues. Now that that's mostly done (one bigger thing left), activity from my side will probably decrease somewhat.
@heaven00: We would definitely love any help we can get. In particular #48 and #49 are some simpler long-standing, bugs that need some unit tests and implementation.

**Comment by heaven00** [comment]
would look into it ^_^

**Comment by whereswaldon** [comment]
@lgierth I am a collaborator, as is @alexander255, and we're doing what we have time to do. Another maintainer would be lovely though. With 3, I think we could safely close this issue.
On another note, would it be possible for @alexander255 or I to have admin access to the repo? We can't add integrations without it (I would love to add Codacy).
