### ISSUE TITLE
Add HEAD option / ignore result for some requests

### ISSUE THREAD

**Issue by mguentner** [ipfs/py-ipfs-http-client#82]
For some requests it makes sense to use HEAD over GET if it is only
relevant whether the request succeeded or not.

Background:

`client.repo_gc()` can potentially return many values (scale: easily 10-100k) depending on how much garbage was collected.
It takes quite some time to parse and decode (`json`) all that even if the result does not matter
inside the calling function.
Most of the time you do not need to know the hashes of the garbage.

**Comment by whereswaldon** [comment]
You know, that's a fantastic point. Would you care to have a go implementing it?

**Comment by lordcirth** [comment]
I've started on this.

**Comment by lordcirth** [comment]
@alexander255 Can you merge this? Not sure who to ping.

**Comment by alexander255** [comment]
This has been merged.
